version: 2.1

parameters:
 test_type:
  type: string
  default: ""
 test_category:
  type: string
  default: ""

workflows:
  build_projects:
    jobs:
    - build_projects:
       name: Building projects
       context: snowcontext
       filters:
            branches:
               ignore: 
                 - master
				 
jobs:
  build_projects:
      docker: 
       - image: mcr.microsoft.com/dotnet/sdk:6.0
      resource_class: small
      steps:
        - checkout        
        - run: 
           name: Build UI Tests project
           command: dotnet build "FacebookTest\NackademinUITest.csproj" --source $NUGET_PACKAGE_REGISTRY_URL
           
  run_saas_ui_tests:
    docker: 
     - image: mcr.microsoft.com/dotnet/sdk:6.0
    parameters:
      browser:
        type: string
        default: chrome
    environment:
      type: string
      default: dev
    steps:
     - checkout
     - ensure_credentials_provider
     - install_xunit_to_junit_tool 
     - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
     - setup_remote_docker:
          docker_layer_caching: false
     - run:
        name: Install Docker client
        command: |
          set -x
          VER="20.10.9"
          curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          mv /tmp/docker/* /usr/bin
     - run:
        name: Run UI Tests
        no_output_timeout: 40m
        command: |
           echo $DOCKER_PASSWORD | docker login $CONTAINER_REGISTRY_URL -u $DOCKER_USERNAME --password-stdin
           export ENVIRONMENT=<< parameters.environment >>
           export BROWSER=<< parameters.browser >>
           export FEED_URL=$NUGET_PACKAGE_REGISTRY_URL
           docker-compose -f "SaaS.UI.Tests/docker-compose.yml" run run-tests
     - run:
        name: Show all containers with statuses
        command: docker ps -a
     - run:
        name: Get Test execution result
        command: |
                 containerId=$(docker ps -aqf "name=saasuitests_run-tests")
                 echo "Container Id $containerId"
                 logs=$(docker logs -n 2 "$containerId")
                 echo "$logs"
                 case "$logs" in *"Passed!"*)
                 echo "Test execution was successful" && exit 0;;
                 *) echo "Test execution failed" && exit 1;;
                 esac
     - run: 
        name: Copy project folder from docker container
        when: always
        command: |
                containerId=$(docker ps -aqf "name=saasuitests_run-tests")
                docker start $containerId
                echo "Container Id- $(docker ps -aq)"
                docker cp $containerId:/SaaS.UI.Tests OutputFolder
     - run:
        name: Convert xunit file to junit
        command: |
           dotnet xunit-to-junit "OutputFolder/Xunit_result.xml" "OutputFolder/JunitResults/Junit_result.xml"
        when: always
     - store_test_results:
        path: OutputFolder/JunitResults
     - store_artifacts:
        path: OutputFolder/bin/Debug/net6.0/Screenshots
     - store_artifacts:
        path: OutputFolder/JunitResults
     - run: 
        name: Docker compose down
        when: always
        command: |
            export BROWSER=<< parameters.browser >>
            cd SaaS.UI.Tests
            docker-compose down